POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"guest",
    "password":"1234"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"1234"
}

###
GET http://localhost:5000/api/types

###
POST http://localhost:5000/api/types
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjA4ZWEyZmJlZTk4ZTkzZDRiZWU4ZTMiLCJpYXQiOjE2NDc2ODYyNDF9.-K-sSOpjBvNS7ZvUh5jugCsIKqA7oOgJ_h0EDp1_3rc

{
    "nameType":"Thức ăn khô 1"
}


###
GET http://localhost:5000/api/items/type/6235b7d696a508aa0ed368d7




###
POST http://localhost:5000/api/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNkNGIwMTM3ZTQzMmY4YzliODlmMTYiLCJpYXQiOjE2NTEzNzM5NjR9.E7Hg0JgD_X3spCL-qC-NH0JeQ-QHNDk7PWvs4pe-0eM

{
    "itemName":"Chả thịt heo Wrap",
    "quantily": 20,
    "priceImport":60000,
    "priceExport":100000,
    "description":"Dùng ngay khi mở gói",
    "pathImage":"https://product.hstatic.net/1000238938/product/023100281964_medium.jpg",
    "type":"6235b58b36f995f40365b1e8"
}



###
GET http://localhost:5000/api/items/type/6235b58b36f995f40365b1e8



###
POST http://localhost:5000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjA4ZWEyZmJlZTk4ZTkzZDRiZWU4ZTMiLCJpYXQiOjE2NDc2ODYyNDF9.-K-sSOpjBvNS7ZvUh5jugCsIKqA7oOgJ_h0EDp1_3rc

{
    "item": "6235c28744aa7b97d4a56e41"
}

###
POST http://localhost:5000/api/items/findItems/
Content-Type: application/json

{
    "name":"PetFoody"
}

###
PUT http://localhost:5000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjA4ZWEyZmJlZTk4ZTkzZDRiZWU4ZTMiLCJpYXQiOjE2NTIyOTkxMzJ9.R3T-nKUpM-UVePrsVZcrkiEmbh_rVfXHcuQVe_DKPYs

{
    "user":"6208ea2fbee98e93d4bee8e3",
    "item":"6235c26444aa7b97d4a56e3d",
    "quantily":5
}


###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjdhNDUwOGE0M2Y4ODJkZGNjYTNhMWIiLCJpYXQiOjE2NTI1ODU1MTd9.nHTBKJfmE1Euzst_Req3yVn33jjmZdGT1XuJrq2NXUg

###
PUT http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjdhNDUwOGE0M2Y4ODJkZGNjYTNhMWIiLCJpYXQiOjE2NTI1ODU1MTd9.nHTBKJfmE1Euzst_Req3yVn33jjmZdGT1XuJrq2NXUg

{
    "fullname": "Lê Thái Nhật Nam",
    "phone": "0963005441",
    "email": "nhatnam11052000@gmail.com",
    "address": "336, Hưng Thành Đông, Long Hưng B, Lấp Vò, Đồng Tháp"
}

###
GET http://localhost:5000/api/orders/6283052deb14913fcfe55298
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjgxZTJjNWJmZTc1YmUyM2FjOWNjYmUiLCJpYXQiOjE2NTI3MjU2OTh9.vR7003vfM3bMlZt4L0t0yqVJT6lZVf_roC--aa2zHyA

###
GET http://localhost:5000/api/orderDetail/628294e68991728f38170447

##3
DELETE http://localhost:5000/api/orders
Content-Type: application/json

{
    
    "order":"62830bee057fee47fbf0d39e"
}

###
GET http://localhost:5000/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjgwOTVmNmY4MTZkYzY1MTcyYjdiMmYiLCJpYXQiOjE2NTI3Nzg4ODl9.0PaNwYoCLjApY2Ru_OME8oUytYdkyRwzHxsYabaWu-A


###
GET http://localhost:5000/api/cart/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjgwOTVmNmY4MTZkYzY1MTcyYjdiMmYiLCJpYXQiOjE2NTI4NDkwMDB9.7uMoDJs-cfDESbboERcirV6UsrTg52NTTczaFKU7Z2Q